<?php
session_start();
include('../admin_panel/db_connection.php');
// Check if the user is logged in and is a stylist
if (!isset($_SESSION['id']) || $_SESSION['role'] !== 'stylist') {
    header('Location: login.php');
    exit();
}

$stylist_id = $_SESSION['id'];

// Fetch today's appointments for the stylist
$today_date = date('Y-m-d');
$appointments_sql = "SELECT * FROM appointments WHERE stylist_id = '$stylist_id' AND appointment_date = '$today_date' AND status = 'approved'";
$appointments_result = $conn->query($appointments_sql);

// Fetch future appointments for the stylist
$future_appointments_sql = "SELECT * FROM appointments WHERE stylist_id = '$stylist_id' AND appointment_date > '$today_date' AND status = 'approved'";
$future_appointments_result = $conn->query($future_appointments_sql);

// Fetch total commission generated by the stylist
$commission_sql = "
    SELECT SUM(s.price * (u.commission_rate / 100)) AS total_commission 
    FROM appointments a
    JOIN services s ON a.service_id = s.id
    JOIN users u ON a.stylist_id = u.id
    WHERE a.stylist_id = '$stylist_id' AND a.status = 'approved'
";
$commission_result = $conn->query($commission_sql);
$total_commission = $commission_result->fetch_assoc()['total_commission'] ?? 0.00;

$conn->close();
?>

<!DOCTYPE html>
<html>
<head>
    <title>Stylist Dashboard</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .container { max-width: 800px; margin: auto; padding: 20px; border: 1px solid #ccc; border-radius: 5px; }
        h1, h2 { text-align: center; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        table th, table td { padding: 10px; border: 1px solid #ccc; }
        table th { background-color: #f0f0f0; }
    </style>
</head>
<body>
<div class="container">
    <h1>Welcome, Stylist!</h1>
    <h2>Your Dashboard</h2>
    
    <h3>Total Commission: $<?= number_format($total_commission, 2) ?></h3>
    
    <h3>Today's Appointments</h3>
    <?php if ($appointments_result->num_rows > 0): ?>
        <table>
            <thead>
                <tr>
                    <th>Client Name</th>
                    <th>Service</th>
                    <th>Time Slot</th>
                    <th>Appointment Date</th>
                </tr>
            </thead>
            <tbody>
                <?php while ($appointment = $appointments_result->fetch_assoc()): ?>
                    <tr>
                        <td><?= $appointment['user_name'] ?></td>
                        <td><?= $appointment['service_id'] ?></td>
                        <td><?= $appointment['time_slot_id'] ?></td>
                        <td><?= $appointment['appointment_date'] ?></td>
                    </tr>
                <?php endwhile; ?>
            </tbody>
        </table>
    <?php else: ?>
        <p>No appointments for today.</p>
    <?php endif; ?>

    <h3>Future Appointments</h3>
    <?php if ($future_appointments_result->num_rows > 0): ?>
        <table>
            <thead>
                <tr>
                    <th>Client Name</th>
                    <th>Service</th>
                    <th>Time Slot</th>
                    <th>Appointment Date</th>
                </tr>
            </thead>
            <tbody>
                <?php while ($future_appointment = $future_appointments_result->fetch_assoc()): ?>
                    <tr>
                        <td><?= $future_appointment['user_name'] ?></td>
                        <td><?= $future_appointment['service_id'] ?></td>
                        <td><?= $future_appointment['time_slot_id'] ?></td>
                        <td><?= $future_appointment['appointment_date'] ?></td>
                    </tr>
                <?php endwhile; ?>
            </tbody>
        </table>
    <?php else: ?>
        <p>No future appointments.</p>
    <?php endif; ?>
</div>
</body>
</html>
